### PR TITLE
[Notification] New API

### PR DESCRIPTION
**Pull request by eddieantonio**
I decided to base my Node SPARQL interface on your project, but I made quite a few changes. I upped the version to 0.3.0, since it still uses the formatter from 0.2.0 (this underwent the least changes). I did merge some outstanding fixes, though I later completely removed the need for those fixes :neutral_face:  

I'm offering this as a pull request, mostly as a notification that this extension exists; It does change things quite a bit. For one, it attempts to provide smarter bind functionality, in an almost prepare statements kind of way. I understand if you would rather not merge this branch.

### CODE REVIEW

**Comment by thomasfr** [comment]
FIrst of all: Thanks for your Pull Request. I really appreciate it!!!
I will take a detailed look into it as soon as possible. At the moment i am not using this module myself in any of my current projects, but i will take a look into it. Do you use this code in any OpenSource project i can check out?

**Comment by eddieantonio** [comment]
No, unfortunately. This has update has been prompted by an internal prototype for a closed-source tool! That said, in terms of examples, the new test suite should provide plenty--especially `dbpedia-spec.js`. If I have time tonight, I'll convert all of the README examples to specs, tested with DBPedia and MeSH (what I'm using this library for).

**Comment by thomasfr** [comment]
Could you also merge upstream and merge the changes?

**Comment by eddieantonio** [comment]
Done!

**Comment by rom1504** [comment]
any news on this ?

**Comment by eddieantonio** [comment]
@rom1504 Since I did not get a reply from @thomasfr, I published my fork as [sparql-client-2](https://www.npmjs.com/package/sparql-client-2). You can find the source [here](https://github.com/eddieantonio/node-sparql-client).

**Comment by rom1504** [comment]
@eddieantonio I think I will be using yours then, thanks !

**Pull request closed without merging**
